config/routes.rb
Rails.application.routes.draw do
  root to: "pao_records#index"
  resources :pao_records do
    get :random, on: :collection
  end

end

app/models/pao_record.rb
class PaoRecord < ActiveRecord::Base
  validates_presence_of :pao_number, :pao_person, :pao_action, :pao_object, :pao_image_url
  validates_uniqueness_of :pao_number, :pao_person, :pao_action, :pao_object, :pao_image_url

  scope :by_pao_number, -> { order :pao_number }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :error, :success
end

app/controllers/pao_records_controller.rb
class PaoRecordsController < ApplicationController
  before_filter :authenticate

  def index
    @pao_records = PaoRecord.by_pao_number
  end

  def new
    @pao_record = PaoRecord.new
  end

  def create
    @pao_record = PaoRecord.new pao_record_params
    if @pao_record.save
      redirect_to :pao_records, notice: "PAO successfully created"
    else
      flash.now[:error] = "One or more errors prevented the PAO creation: #{@pao_record.errors.full_messages.join ', '}"
      render :new
    end
  end

  def show
    @pao_record = PaoRecord.find params[:id]
  end

  def edit
    @pao_record = PaoRecord.find params[:id]
  end

  def update
    @pao_record = PaoRecord.find params[:id]
    if @pao_record.update_attributes pao_record_params
      redirect_to :pao_records, notice: "PAO successfully updated"
    else
      flash.now[:error] = "One or more errors prevented the PAO update: #{@pao_record.errors.full_messages.join ', '}"
      render :edit
    end
  end

  def random
    @pao_record = PaoRecord.order('random()').first
    @displayed_info = @pao_record[%w(pao_number pao_person pao_action pao_object).sample]
  end

  private

  def authenticate
    authenticate_or_request_with_http_basic('PAO') do |login, password|
      login == ENV['LOGIN']
    end
  end

  def pao_record_params
    params.require(:pao_record).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :error
      "alert-danger"
    when :alert
      "alert-warning"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/views/layouts/_flash_messages.html.slim
- flash.each do |type, message|
  = content_tag :div, class: "alert #{bootstrap_class_for type} fade in alert-dismissable" do
    button.close{type="button" data-dismiss="alert"} &times;
    = message

app/views/layouts/_topbar.html.slim
.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      a.navbar-brand href="/"
        |Pao
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to "Add new", new_pao_record_path
        li= link_to "Random", random_pao_records_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Pao
    meta{charset="utf-8"}
    meta{name="viewport" content="width=device-width, initial-scale=1.0"}

    = stylesheet_link_tag "application", media: "all"
    link{rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    = csrf_meta_tags
  body
    = render "layouts/topbar"

    .container
      = render "layouts/flash_messages", flash: flash
      = yield


    = javascript_include_tag "application"
    script{src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}

app/views/pao_records/_form.html.slim
= form_for @pao_record, html: { class: "form-inline" } do |f|
  .form-group
    = f.text_field :pao_number, class: "form-control", placeholder: "Nb", size: 2, autofocus: true
  .form-group
    = f.text_field :pao_person, class: "form-control", placeholder: "Person"
  .form-group
    = f.text_field :pao_action, class: "form-control", placeholder: "Action"
  .form-group
    = f.text_field :pao_object, class: "form-control", placeholder: "Object"
  .form-group
    = f.url_field :pao_image_url, class: "form-control", placeholder: "Image URL"
  = f.submit "Save", class: "btn btn-primary"

app/views/pao_records/edit.html.slim
h1 Edit #{@pao_record.pao_number}
= render "form"

app/views/pao_records/index.html.slim
table.table
  thead
    tr
      th Number
      th Person
      th Action
      th Object
      th Edit
  tbody
    - @pao_records.each do |pao_record|
      tr
        td= link_to pao_record.pao_number, pao_record
        td= pao_record.pao_person
        td= pao_record.pao_action
        td= pao_record.pao_object
        td= link_to "edit", edit_pao_record_path(pao_record)

app/views/pao_records/new.html.slim
h1 New PAO
= render "form"

app/views/pao_records/random.html.slim
h1= @displayed_info

p
  = link_to "See record", @pao_record
  |&nbsp;&nbsp;&nbsp;
  = link_to "Random", random_pao_records_path

app/views/pao_records/show.html.slim
h1 #{@pao_record.pao_number}: #{@pao_record.pao_person} #{@pao_record.pao_action} #{@pao_record.pao_object}

p= link_to "Random", random_pao_records_path

img src="#{@pao_record.pao_image_url}"